<link rel="stylesheet" type="text/css" media="screen" href="css/all.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/navBar.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/footer.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/header.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/competence.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/project.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/service.css">