<!-- DESKTOP -->
<nav id="navbar-desktop" class="navbar navbar-expand-lg fixed-top">
    <div class="content">
        <div class="logo">
            <h5 class="h5">MAXIME TOURNIER</h5>
        </div>
        <div class="items">
            <ul>
                <li><a href="#header">A propos</a></li>
                <li><a href="#competence">Compétences</a></li>
                <li><a href="#project">Expériences</a></li>
                <li><a href="">Histoire</a></li>
                <li><a href="#service">Services</a></li>
            </ul>
        </div>
        <div class="number">
            <a class="btn-numero" href="tel:+33611112669">
                <div class="svg-wrapper">
                    <i class="fa-solid fa-phone"></i>
                </div>
                <span>06 11 11 26 69</span>
            </a>
        </div>
    </div>
</nav>
<!-- / DESKTOP -->

<!-- MOBILE -->

<div class="navbar fixed-top" id="navbar-mobile">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">MAXIME TOURNIER</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">

            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#header">A propos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#competence">Compétences</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#project">Expériences</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Histoire</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#service">Services</a>
                    </li>
                    <a class="btn-numero" style="margin-top: 10px">
                        <i class="fa-solid fa-phone"></i>
                        <span>06.11.11.26.69</span>
                    </a>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- /MOBILE -->
