<nav id="navbar">
    <div class="content">
        <div class="logo">
            <h5 class="h5">MAXIME TOURNIER</h5>
        </div>
        <div class="items">
            <ul>
                <li><a href="">A propos</a></li>
                <li><a href="">Expériences</a></li>
                <li><a href="">Compétences</a></li>
                <li><a href="">Histoire</a></li>
                <li><a href="">Services</a></li>
            </ul>
        </div>
        <div class="number">
            <button class="btn-donate">
                <i class="fa-solid fa-phone"></i>
                06.11.11.26.69
            </button>
        </div>
    </div>
</nav>