<!-- DESKTOP -->
<nav id="navbar-desktop">
    <div class="content">
        <div class="logo">
            <h5 class="h5">MAXIME TOURNIER</h5>
        </div>
        <div class="items">
            <ul>
                <li><a href="#header">A propos</a></li>
                <li><a href="#competence">Compétences</a></li>
                <li><a href="#project">Expériences</a></li>
                <li><a href="">Histoire</a></li>
                <li><a href="#service">Services</a></li>
            </ul>
        </div>
        <div class="number">
            <button class="btn-donate">
                <i class="fa-solid fa-phone"></i>
                06.11.11.26.69
            </button>
        </div>
    </div>
</nav>
<!-- / DESKTOP -->

<!-- MOBILE -->

<div class="navbar" id="navbar-mobile">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MAXIME TOURNIER</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#header">A propos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#competence">Compétences</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#project">Expériences</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Histoire</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#service">Services</a>
          </li>
          <button class="btn-donate">
                <i class="fa-solid fa-phone"></i>
                06.11.11.26.69
        </button>
        </ul>
      </div>
    </div>
  </div>
</div>

<!-- /MOBILE -->
